p8105_hw5_hj2660
================
Hyun Jin Jung
2023-11-15

# Problem 1

Describe the raw data.

``` r
homocide_df = read.csv("data-homicides-master/homicide-data.csv") 
```

Create a city_state variable (e.g. “Baltimore, MD”) and then summarize
within cities to obtain the total number of homicides and the number of
unsolved homicides (those for which the disposition is “Closed without
arrest” or “Open/No arrest”).

``` r
tidy_homocide = homocide_df |>
  mutate(city_state = str_c(city, state, sep = ","))

sum_homocide = tidy_homocide |>
  group_by(city_state) |>
  summarize(
    total_homocides = n(),
    total_unsolved_homocides = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))
  )

sum_homocide
```

    ## # A tibble: 51 × 3
    ##    city_state     total_homocides total_unsolved_homocides
    ##    <chr>                    <int>                    <int>
    ##  1 Albuquerque,NM             378                      146
    ##  2 Atlanta,GA                 973                      373
    ##  3 Baltimore,MD              2827                     1825
    ##  4 Baton Rouge,LA             424                      196
    ##  5 Birmingham,AL              800                      347
    ##  6 Boston,MA                  614                      310
    ##  7 Buffalo,NY                 521                      319
    ##  8 Charlotte,NC               687                      206
    ##  9 Chicago,IL                5535                     4073
    ## 10 Cincinnati,OH              694                      309
    ## # ℹ 41 more rows

For the city of Baltimore, MD, use the prop.test function to estimate
the proportion of homicides that are unsolved; save the output of
prop.test as an R object, apply the broom::tidy to this object and pull
the estimated proportion and confidence intervals from the resulting
tidy dataframe.

``` r
baltimore_df =
  sum_homocide |>
  filter(city_state == "Baltimore,MD") 

baltimore_result = prop.test(
  x = baltimore_df$total_unsolved_homocides,
  n = baltimore_df$total_homocides)

#apply broom::tidy and pull the estimated proportion and CI intervals
baltimore_tidy_result =
  broom::tidy(baltimore_result) |>
  select(estimate, conf.low, conf.high)

baltimore_tidy_result
```

    ## # A tibble: 1 × 3
    ##   estimate conf.low conf.high
    ##      <dbl>    <dbl>     <dbl>
    ## 1    0.646    0.628     0.663

The estimated proportion is 0.646, and its 95% confidence interval is
\[0.628, 0.663\].

Now run prop.test for each of the cities in your dataset, and extract
both the proportion of unsolved homicides and the confidence interval
for each. Do this within a “tidy” pipeline, making use of purrr::map,
purrr::map2, list columns and unnest as necessary to create a tidy
dataframe with estimated proportions and CIs for each city.

``` r
city_prop = sum_homocide |>
  group_by(city_state)
```

Create a plot that shows the estimates and CIs for each city – check out
geom_errorbar for a way to add error bars based on the upper and lower
limits. Organize cities according to the proportion of unsolved
homicides.

# Problem 2

This zip file contains data from a longitudinal study that included a
control arm and an experimental arm. Data for each participant is
included in a separate file, and file names include the subject ID and
arm.

Create a tidy dataframe containing data from all participants, including
the subject ID, arm, and observations over time:

Start with a dataframe containing all file names; the list.files
function will help

``` r
comb_df = 
  tibble(
    files = list.files("data/"),
    path = str_c("data/", files)
  ) |> 
  mutate(data = map(path, read_csv)) |> 
  unnest()
```

Iterate over file names and read in data for each subject using
purrr::map and saving the result as a new variable in the dataframe

Tidy the result; manipulate file names to include control arm and
subject ID, make sure weekly observations are “tidy”, and do any other
tidying that’s necessary

``` r
tidy_df = comb_df |> 
  mutate(
    files = str_replace(files, ".csv", ""),
    group = str_sub(files, 1, 3),
    ID = str_sub(files, 5, 7)) |>
  pivot_longer(week_1:week_8,names_to = "week", values_to = "observation",names_prefix = "week_") |>
  mutate(week = as.numeric(week)) |>
  select(group, ID, week, observation)

tidy_df
```

    ## # A tibble: 160 × 4
    ##    group ID     week observation
    ##    <chr> <chr> <dbl>       <dbl>
    ##  1 con   01        1        0.2 
    ##  2 con   01        2       -1.31
    ##  3 con   01        3        0.66
    ##  4 con   01        4        1.96
    ##  5 con   01        5        0.23
    ##  6 con   01        6        1.09
    ##  7 con   01        7        0.05
    ##  8 con   01        8        1.94
    ##  9 con   02        1        1.13
    ## 10 con   02        2       -0.88
    ## # ℹ 150 more rows

Make a spaghetti plot showing observations on each subject over time,
and comment on differences between groups.

``` r
spagetti_plot = tidy_df |>
  ggplot(aes(x = week, y = observation, color = ID)) +
  geom_line() +
  geom_point() + 
  facet_grid(~group) +
  labs(x = 'Week', y = 'Observation', title = 'Observations on each Subject Over Time')

spagetti_plot
```

![](p8105_hw5_hj2660_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->
